
```{r}

library(DESeq2)
library(dplyr)
library(ggplot2)
library(ComplexHeatmap)
library(circlize)
library(sporkforlife)



all_samples.counts <- read.delim("/rds/projects/c/croftap-croftapcarcia/RNA_ATAC_JAN2025/RNAseq/count/pipline/results/featurecounts/all_samples.counts.txt", comment.char="#", row.names = 1)




```

```{r}

all_counts <- all_samples.counts

all_counts <- all_counts %>% dplyr::select(-c(Chr, Start,End, Strand, Length))    #remove non-essential columns

colnames(all_counts) <- c("R6", "R1", "R3", "R4", "R5", "R2")  #rename columns


all_counts <- all_counts[,c(2,6,3,4,5,1)]

#make meta data from count matrix
meta_data=colnames(all_counts)
meta_data<-as.data.frame(meta_data)

#add a condition column
meta_data$condition <- c(rep("ctrl", 3), rep("CAR", 3))
colnames(meta_data)<-c("sample", "condition")

#make factors
meta_data$sample<-as.factor(meta_data$sample)
meta_data$condition<-as.factor(meta_data$condition)
```


```{r}
order <- c("ctrl", "CAR")  #the order you want your conditions to appear

result <- process_deseq_PCA(counts = all_counts, 
                             meta_data = meta_data, 
                             relevel_condition = order, 
                             min_gene_count = 200)

dds <- result$dds
pca_plot <- result$pca_plot
pca_plot

```
```{r}


library(gsfisher)
annotation_gs <- fetchAnnotation(species="mm", ensembl_version=NULL, ensembl_host=NULL)



custom_colors <- c("ctrl" = "red", "CAR" = "blue")

#define order of how you want to plot the heatmap
custom_order <- c("ctrl", "CAR")


run_deseq_contrast_heatmap(dds = dds, 
                           meta_data = meta_data, 
                           targetvar = "condition", 
                           p_value_threshold = 0.05, 
                           log2fc_threshold = 0.25, 
                           condition_colors = custom_colors,
                           condition_order = custom_order,
                           go_analysis = F, 
                           organism = "mm", 
                           annotation_gs = annotation_gs)



results_all_f <- results_all %>% filter(padj < 0.05)


index <- match(results_all_f$gene, annotation_gs$ensembl_id)
results_all_f$gene_name <- annotation_gs$gene_name[index]

write.csv(results_all_f, "/rds/projects/c/croftap-croftapcarcia/RNA_ATAC_JAN2025/RNAseq/analysis/DEGs.csv")

```






```{r}

condition_colors <- c("ctrl" = "red", "CAR" = "blue")

#define order of how you want to plot the heatmap
condition_order <- c("ctrl", "CAR")

targetvar = "condition"

p_value_threshold = 0.05

log2fc_threshold = 0.25

conds <- data.frame(t(combn(unique(as.character(meta_data[[targetvar]])), 
        2)))
    results_df <- apply(conds, 1, function(cp) {
        print(cp)
        results_df <- data.frame(DESeq2::results(dds, contrast = c(targetvar, 
            cp[2], cp[1])))
        results_df[["gene"]] <- rownames(results_df)
        results_df[["comparison"]] <- paste0(cp[2], "_vs_", cp[1])
        results_df
    })
    results_all <- Reduce(rbind, results_df)
    DEGs_f <- results_all %>% filter(padj < p_value_threshold, 
        abs(log2FoldChange) > log2fc_threshold) %>% mutate(score = log2FoldChange * 
        (-log10(pvalue))) %>% arrange(desc(abs(score)))
    assign("DEGs_f", DEGs_f, envir = .GlobalEnv)
    DEGs_f$cluster <- "NO"
    DEGs_f$cluster[DEGs_f$log2FoldChange > 0.001] <- "UP"
    DEGs_f$cluster[DEGs_f$log2FoldChange < -0.001] <- "DOWN"
    go.results <- NULL
    go.results.top <- NULL
    assign("results_all", results_all, envir = .GlobalEnv)
    
    
    vsd <- vst(dds, blind = TRUE)
    gene_filter <- unique(DEGs_f$gene)
    vsd_mat <- assay(vsd)[rownames(vsd) %in% gene_filter, ]
    scale_sub_vsd <- t(scale(t(vsd_mat)))
    if (is.null(condition_colors)) {
        condition_colors <- RColorBrewer::brewer.pal(n = length(unique(meta_data[[targetvar]])), 
            name = "Set1")
        names(condition_colors) <- unique(meta_data[[targetvar]])
    }
    if (!is.null(condition_order)) {
        meta_data[[targetvar]] <- factor(meta_data[[targetvar]], 
            levels = condition_order)
        ordered_indices <- order(meta_data[[targetvar]])
        scale_sub_vsd <- scale_sub_vsd[, ordered_indices]
        meta_data <- meta_data[ordered_indices, ]
    }
    condition_ann <- meta_data[[targetvar]]
    top_annotation <- HeatmapAnnotation(condition = condition_ann, 
        col = list(condition = condition_colors))
    assign("scale_sub_vsd", scale_sub_vsd, envir = .GlobalEnv)
    assign("top_annotation", top_annotation, envir = .GlobalEnv)
    print(Heatmap(scale_sub_vsd, top_annotation = top_annotation, 
        col = colorRamp2(c(-1.5, 0, 1.5), c("blue", "white", 
            "red")), row_names_gp = gpar(fontsize = 4), cluster_columns = FALSE, 
        cluster_rows = TRUE, show_row_names = FALSE, show_column_names = FALSE, 
        border = TRUE))
    
    
results_all_f <- results_all %>% filter(padj < 0.05)


index <- match(results_all_f$gene, annotation_gs$ensembl_id)
results_all_f$gene_name <- annotation_gs$gene_name[index]
    
    
```





```{r}


scale_sub_vsd <- scale_sub_vsd %>% as.data.frame()


index <- match(rownames(scale_sub_vsd), annotation_gs$ensembl_id)
rownames(scale_sub_vsd) <- annotation_gs$gene_name[index]


scale_sub_vsd <- as.matrix(scale_sub_vsd)



annotation_col <- data.frame(
  Group = c("ctrl", "ctrl", "ctrl", "CAR", "CAR", "CAR") # Example groupings
)
rownames(annotation_col) <- colnames(data) # Match to column names of the data

# Colors for annotations
annotation_colors <- list(
  Group = c(ctrl = "yellow", CAR = "green")
)


pheatmap(scale_sub_vsd[c("Cxcl11", "Clec12a", "Cldn13",  "Acta1", "C7", "Cd79a", "Prg4", "F13a1", "Col11a1", "Col8a2", "Col23a1", "Krt12"),], color=colorRampPalette(c("navy", "white", "red"))(15), border_color = "black")


pheatmap(scale_sub_vsd[c("Col11a1", "Col8a2", "Col23a1", "C1qtnf3", "Mmp13", "Lrrc4c", "Fbn2", "Thbs4", "Tnc", "Spon1", "Il1rl1", "Tnfsf11"),], color=colorRampPalette(c("navy", "white", "red"))(15), border_color = "black", cluster_cols = F)


Heatmap(scale_sub_vsd,
        name = "Expression",
        cluster_rows = T,
        cluster_columns = F,
        row_title_rot = 0,
        row_title_gp = gpar(fontsize = 10, fontface = "bold"),
        row_names_gp = gpar(fontsize = 9),
        column_names_gp = gpar(fontsize = 10),
        show_row_dend = T,
        show_column_dend = T,
        heatmap_legend_param = list(title = "Expression\nValue"), show_row_names = F, border = T)


```

```{r}
library(EnhancedVolcano)

genes=c("Col11a1", "Col8a2", "Col23a1", "C1qtnf3", "Mmp13", "Lrrc4c", "Fbn2", "Thbs4", "Tnc", "Spon1", "Il1rl1", "Tnfsf11")


index <- match(rownames(results_all), annotation_gs$ensembl_id)
results_all$gene_name <- annotation_gs$gene_name[index]

EnhancedVolcano(results_all,
    lab = results_all$gene_name,
    x = 'log2FoldChange',
    y = 'padj',
    title = 'title',
    subtitle = "GEX, red=p_adj<0.05 & FC > 0.25",
    pCutoff = 0.05,
    FCcutoff = 0.25,
    pointSize = 3.0,
    labSize = 5,
    cutoffLineType = 'twodash',
    cutoffLineWidth = 0.3,
    gridlines.major = FALSE,
    gridlines.minor = FALSE,
      legendPosition = 'none',
    legendLabSize = 10,
    legendIconSize =3.0,
    legendLabels=c('NS','p<0.05 & FC > 0.25'),
    col=c('black', 'black', 'black', 'red3'),
          drawConnectors = TRUE,
    widthConnectors = 0.3,
     xlab = bquote(~Log[2]~ 'fold change'),
    boxedLabels = T,
    borderWidth = 0.5, max.overlaps = 10,
    selectLab = c("Kcnj15", "Ddah1", "Prokr2", "Sftpc", "Adgrb3", "Acan", "Fbn2", "Car1", "Ctse", "Ctsg", "Cst7", "Cxcl11", "H2-Aa"))+xlim(-12,10)+ylim(0,12)
```

```{r}
results_down_reg <- results_all %>% filter(padj < 0.05) %>% filter(log2FoldChange < -0.001)

results_down_reg_RNAseq <- results_down_reg


results_up_reg <- results_all %>% filter(padj < 0.05) %>% filter(log2FoldChange > 0.001)

results_up_reg_RNAseq <- results_up_reg

```




```{r}

results_all_f$comparison %>% unique()

index <- match(results_all$gene, annotation_gs$ensembl_id)
results_all$gene_name <- annotation_gs$gene_name[index]

results_all_f$cluster <- "NO"
    results_all_f$cluster[results_all_f$log2FoldChange > 0.05] <- "UP"
    results_all_f$cluster[results_all_f$log2FoldChange < -0.05] <- "DOWN"

go.results <- runGO.all(results=results_all_f,
                  background_ids = rownames(results_all), gene_id_col="gene", gene_id_type="ensembl", sample_col="cluster", p_col="padj", p_threshold=0.05,
                  species = "mm")
go.results <- filterGenesets(go.results)
go.results.top <- go.results %>% group_by(cluster) %>% top_n(n=5, -p.val)
sampleEnrichmentDotplot(go.results.top, selection_col = "description", selected_genesets = unique(go.results.top$description), sample_id_col = "cluster", fill_var = "odds.ratio", maxl=50, title="Go term",rotate_sample_labels = T)


sampleEnrichmentDotplot(go.results, selection_col = "description", selected_genesets = c("regulation of inflammatory response", "extracellular matrix organization", "MHC protein complex binding", "antigen processing and presentation of peptide antigen"), sample_id_col = "cluster", fill_var = "odds.ratio", maxl=50, title="Go term",rotate_sample_labels = T)+ggtitle("CAR treated vs ctrl")



library(gsfisher)
annotation_gs <- fetchAnnotation(species="mm", ensembl_version=NULL, ensembl_host=NULL)

vsd <- vst(dds, blind = TRUE)
vsd_mat <- assay(vsd)
norm_expr_mat<- t(scale(t(vsd_mat)))

ensembl_ids <- rownames(norm_expr_mat)

# Match each Ensembl ID to its gene name
idx <- match(ensembl_ids, annotation_gs$ensembl_id)

# Replace rownames with gene names (keeping original if no match)
rownames(norm_expr_mat) <- ifelse(
  is.na(idx),
  ensembl_ids,  
  annotation_gs$gene_name[idx]
)


Heatmap(norm_expr_mat[c("Il6", "Il18", "Il17f", "Il17rc", "Thy1", "Cxcl5", "Cxcl10", "Ccl20", "Ccl19", "Tnfrsf10b", "Tnfrsf9", "Tnfrsf23"),c(1,2,3,4,5,6)], border=T, show_row_names = T, cluster_columns = F,c("blue", "white", "red"))

###########qiescent genes#########
Heatmap(norm_expr_mat[c("Creb5", "Foxo1", "Sox5"),c(1,2,3,4,5,6)], border=T, show_row_names = T, cluster_columns = F,c("blue", "white", "red"))


Heatmap(norm_expr_mat[c("C3", "C1qa", "C1qb", "C1ra", "Cd55", "C1s1", "C4b", "C3ar1", "Cr1l", "Ctsf", "Fhl1", "Cfb", "Cfp", "Cfh"),c(1,2,3,4,5,6)], border=T, show_row_names = T, cluster_columns = F,c("blue", "white", "red"))

Heatmap(norm_expr_mat[c("Fap", "Tnfsf11", "Tnfrsf11b", "Mmp3", "Mmp9", "Mmp13", "Fn1", "Postn", "Hif1a", "Col1a1", "Col1a2", "Col3a1", "Col6a1", "Col6a3"),c(1,2,3,4,5,6)], border=T, show_row_names = T, cluster_columns = F,c("blue", "white", "red"))

```

```{r}
results_all_f <- results_all %>% filter(padj < 0.05)


index <- match(results_all_f$gene, annotation_gs$ensembl_id)
results_all_f$gene_name <- annotation_gs$gene_name[index]

FilteredGeneID <- unique(results_all_f$gene)
        index <- match(FilteredGeneID, annotation_gs$gene_name)
        ensemblUni <- annotation_gs$ensembl_id[index]
        ensemblUni <- na.omit(ensemblUni)

        index <- match(results_all_f$gene, annotation_gs$gene_name)
        results_all_f$ensembl <- annotation_gs$ensembl_id[index]
        results_all_f <- na.omit(results_all_f)

        go.results <- runGO.all(results = results_all_f, background_ids = ensemblUni, 
            gene_id_col = "ensembl", gene_id_type = "ensembl", 
            sample_col = "cluster", p_col = "padj", p_threshold = 0.05, 
            species = "mm")
        
        go.results <- filterGenesets(go.results)
        go.results.top <- go.results %>% group_by(cluster) %>% 
            top_n(n = 5, -p.val)
        sampleEnrichmentDotplot(go.results, selection_col = "description", 
            selected_genesets = c("antigen processing and presentation of peptide antigen", "negative regulation of endopeptidase activity", "regulation of cell killing", "signaling receptor inhibitor activity", "negative regulation of immune response", "Notch signaling pathway", "bone remodelling", "regulation of Wnt signaling pathway", "tissue remodelling", "mesenchyme development", "regulation of canonical Wnt signaling pathway", "tissue migration"), 
            sample_id_col = "cluster", fill_var = "odds.ratio", 
            maxl = 50, title = "GO Term Enrichment", rotate_sample_labels = TRUE) + Font(x.text = 12, y.text = 12) + ylab(NULL) +xlab(NULL)

```




